const $=id=>document.getElementById(id);
const choices={style:[['Кінематографічний','cinematic editorial photography, refined color grading'],['Природний','natural lifestyle photography, believable colors'],['Fashion editorial','high-end fashion editorial, confident styling'],['Ретро / плівка','analog film aesthetic, subtle grain, gentle halation'],['Чорно-білий','black-and-white photography, rich tonal separation'],['Студійний','professional studio portrait photography']],light:[['Золота година','warm golden-hour sunlight, soft directional light and gentle rim light'],['М’яке денне','soft diffused daylight, realistic shadows'],['Студійний софтбокс','large softbox key light, subtle fill and controlled shadows'],['Неон / ніч','cinematic neon practical lights at night, controlled highlights'],['Похмурий день','soft overcast daylight, muted colors'],['Контрове світло','backlighting with a delicate rim light, balanced facial exposure']],framing:[['Портрет','head-and-shoulders portrait'],['До пояса','waist-up portrait'],['На повний зріст','full-body composition, include feet'],['Великий план','close-up portrait'],['Загальний план','wide environmental portrait']],quality:[['Висока деталізація','high detail, sharp subject, realistic textures'],['Натуральна шкіра','realistic skin texture with pores, subtle imperfections, no beauty smoothing'],['Редакційна якість','publication-quality editorial finish, refined microcontrast, natural skin texture']]};
for(const [id,values] of Object.entries(choices)) for(const [label,value] of values)$(id).add(new Option(label,value));
const themes=[['Осінній парк','A person in an elegant coat walking through an autumn park, amber leaves and a quiet pathway'],['Міський портрет','A person in minimalist streetwear on a city street, architectural lines and a relaxed confident pose'],['Біля моря','A person in a flowing linen outfit by the sea, ocean breeze and a serene expression'],['Студія','A person in a tailored outfit against a clean studio background, expressive portrait pose']];
for(const [label,idea]of themes){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{$('idea').value=idea;refresh()};$('themes').append(b)}
const iphones=document.createElement('optgroup');iphones.label='Apple iPhone';for(let i=11;i<=18;i++)iphones.append(new Option(`iPhone ${i} Pro Max`,`iPhone ${i} Pro Max`));$('phone').append(iphones);
const pixels=document.createElement('optgroup');pixels.label='Google Pixel';for(let i=4;i<=11;i++)pixels.append(new Option(`Pixel ${i}${i>=6?' Pro':''}${i===11?' · користувацький пресет':''}`,`Google Pixel ${i}${i>=6?' Pro':''}`));$('phone').append(pixels);
for(const [label,value] of PhotoSession.angles)$('angle').add(new Option(label,value));
const shotSettings=PhotoSession.presets.map(p=>({title:p[0],angle:PhotoSession.angles[p[1]][1],framing:choices.framing[p[2]][1],custom:'',pose:p[3]}));
function buildShots(){
 const previous=$('shotOutput').value; $('shotList').replaceChildren();$('shotOutput').replaceChildren(new Option('Уся фотосесія','all'));
 shotSettings.slice(0,Number($('shotCount').value)).forEach((shot,i)=>{
 const card=document.createElement('div');card.className='shot-card';
 const heading=document.createElement('h3');heading.textContent=`${String(i+1).padStart(2,'0')} / ${shot.title}`;card.append(heading);
 const grid=document.createElement('div');grid.className='grid two';
 for(const [key,label,options] of [['angle','Ракурс',PhotoSession.angles],['framing','План',choices.framing]]){
 const wrap=document.createElement('div'),l=document.createElement('label'),select=document.createElement('select');select.id=`shot-${i}-${key}`;l.htmlFor=select.id;l.textContent=label;
 options.forEach(([name,value])=>select.add(new Option(name,value)));select.value=shot[key];select.onchange=()=>{shot[key]=select.value;refresh()};wrap.append(l,select);grid.append(wrap)}card.append(grid);
 for(const [key,label,placeholder] of [['custom','Свій ракурс (замість обраного)','Наприклад: камера праворуч під кутом 45°'],['pose','Поза / дія','Опишіть позу для цього кадру']]){
 const l=document.createElement('label'),input=document.createElement('input');input.id=`shot-${i}-${key}`;input.type='text';input.value=shot[key];input.placeholder=placeholder;l.htmlFor=input.id;l.textContent=label;input.oninput=()=>{shot[key]=input.value;refresh()};card.append(l,input)}
 const hint=document.createElement('p');hint.textContent=PhotoSession.presets[i][4];card.append(hint);$('shotList').append(card);$('shotOutput').add(new Option(`Кадр ${i+1} — ${shot.title}`,String(i)))
 });$('shotOutput').value=[...$('shotOutput').options].some(o=>o.value===previous)?previous:'all';
}
$('shotCount').addEventListener('change',()=>{buildShots();refresh()});$('shotOutput').addEventListener('change',render);buildShots();
let ratio='4:3',device='camera',format='text',current;
for(const r of ['16:9','3:4','4:3','9:16','5:4','4:5','3:2','2:3']){const b=document.createElement('button');b.type='button';b.dataset.ratio=r;b.setAttribute('aria-pressed',String(r===ratio));const icon=document.createElement('span');icon.className='ratio-icon';icon.style.aspectRatio=r.replace(':','/');b.append(icon,document.createTextNode(r));b.onclick=()=>{ratio=r;document.querySelectorAll('[data-ratio]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));refresh()};$('ratios').append(b)}
const lenses={'35':['35 mm','moderately wide environmental portrait, include surrounding context','Ширший кадр із простором та оточенням.'],'50':['50 mm','natural perspective and soft background separation','Природна перспектива та м’яке відділення від фону.'],'80':['80 mm','portrait framing with a soft out-of-focus background','Портрет із м’яким розмиттям заднього плану.'],'125':['125 mm','telephoto portrait look, compressed background, shallow depth of field','Телеоб’єктивний вигляд і виразне відділення від фону.'],'44m':['Helios 44M 58 mm','vintage optical character, gentle contrast, subtle swirly background bokeh','Вінтажний характер, м’який контраст і закручене боке.'],'44-2':['Helios 44-2 58 mm','vintage rendering, expressive swirly bokeh, gentle optical softness around the edges','Вінтажний малюнок і виразне закручене боке.']};
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;document.querySelectorAll('[data-device]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('cameraFields').hidden=device!=='camera';$('phoneFields').hidden=device!=='phone';refresh()});
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{format=b.dataset.format;document.querySelectorAll('[data-format]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});
function refresh(){const lens=lenses[$('lens').value];const equipment=device==='camera'?`${$('camera').value} camera aesthetic, ${lens[0]} lens rendering. ${lens[1]}`:`${$('phone').value} smartphone photography aesthetic, natural mobile-camera rendering, balanced computational processing; no external interchangeable lens`;
current={subject:$('idea').value.trim()||'A person in a minimalist outfit, relaxed confident pose, a quiet city street',style:$('style').value,camera:equipment,lighting:$('light').value,composition:`${$('framing').value}, intentional framing`,angle:$('customAngle').value.trim()||$('angle').value,aspect_ratio:ratio,quality:$('quality').value,reference:$('identity').checked?'Use the attached reference photo as the identity source. Preserve facial features, age, skin tone and natural appearance. Do not reshape or beautify the face.':'No reference image required.',avoid:'Distorted anatomy, extra fingers, plastic skin, excessive sharpening, text, watermarks, unwanted logos.'};
$('equipmentLabel').textContent=device==='camera'?`${$('camera').value.toUpperCase()} / ${lens[0].toUpperCase()}`:$('phone').value.toUpperCase();$('framingLabel').textContent=$('framing').selectedOptions[0].textContent.toUpperCase();$('frame').style.aspectRatio=ratio.replace(':','/');$('ratioLabel').textContent=ratio;$('opticsHint').textContent=device==='camera'?lens[2]:'Стилізація під мобільну фотографію. Зовнішні об’єктиви не додаються.';$('message').textContent='';render()}
function render(){
 const session=$('mode').value==='session';$('sessionFields').hidden=!session;$('shotOutputFields').hidden=!session;$('singleAngleFields').hidden=session;
 $('framing').disabled=session;
 $('resultTitle').textContent=session?'Промпти фотосесії':'Готовий промпт';
 const generate=document.querySelector('.generate');generate.firstChild.textContent=session?'Створити фотосесію ':'Створити промпт ';
 let result=current;
 if(session){const shots=shotSettings.slice(0,Number($('shotCount').value)).map((shot,i)=>PhotoSession.makeShot(current,shot,i,Number($('shotCount').value)));result=$('shotOutput').value==='all'?shots:shots[Number($('shotOutput').value)];}
 $('output').value=format==='json'?JSON.stringify(result,null,2):Array.isArray(result)?result.map(p=>`FRAME ${p.shot_number} / ${p.total_shots}\n\n${PhotoSession.toText(p)}`).join('\n\n────────────────────────\n\n'):PhotoSession.toText(result);
 $('charCount').textContent=`${$('output').value.length} символів`;
 $('framingLabel').textContent=session?`${$('shotCount').value} КАДРІВ`:$('framing').selectedOptions[0].textContent.toUpperCase();
}
$('builder').addEventListener('input',refresh);$('builder').addEventListener('change',refresh);$('builder').addEventListener('submit',e=>{e.preventDefault();refresh();$('message').textContent=$('mode').value==='session'?'Фотосесію оновлено. Оберіть кадр або скопіюйте всю серію.':'Промпт оновлено. Можна копіювати.';if(innerWidth<751)$('output').scrollIntoView({behavior:'smooth',block:'center'})});
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('output').value);$('message').textContent='Промпт скопійовано!'}catch{$('output').focus();$('output').select();$('message').textContent='Виділіть і скопіюйте текст: Ctrl+C або меню копіювання.'}};refresh();
